name: Freestyle Pix
favicon: null
layout_spectrum: 0.51324
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#720000'
    - '#161e69'
    - '#fff660'
    - '#325df7'
    - '#907c1d'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.3480391704943031
  rhythmicContrast: 0
purpose: []
